[package]
name = "tee-scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
tee = { path = "../../tee" }
tokio = { version = "1.39.2", features = ["full"] }

[[bin]]
name = "run_shard_scaling"
path = "rust/run_shard_scaling.rs"